apiVersion: v1
kind: Service
metadata:
  labels:
    name: pre1-escheduler-api
    app: escheduler-api
  name: pre1-escheduler-api
  namespace: shentan-bigdata
spec:
    type: ClusterIprintf("%s,%s,%d:%s\n",__FILE__,__FUNCTION__,__LINE__,"" ); 
  ports:
    - name: escheduler-api
      port: 12345
      targetPort: 12345
      protocol: TCP
  selector:
    name: pod-escheduler-api
    app: escheduler-api
