apiVersion: v1
kind: Service
metadata:
  labels:
    name: %PREFIX%-escheduler-api
    app: escheduler-api
  name: %PREFIX%-escheduler-api
  namespace: %NAMESPACE%
spec:
  type: ClusterIP
  ports:
    - name: escheduler-api
      port: 12345
      targetPort: 12345
      protocol: TCP
  selector:
    name: pod-escheduler-api
    app: escheduler-api
