apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: %PREFIX%-escheduler-master
  namespace: %NAMESPACE% 
spec:
  replicas: %WORKER_NUM%
  template:
    metadata:
      labels:
        name: pod-escheduler-master
        app: escheduler-master
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - image: %HARBOR%/%ES_BACKEND_IMAGE%
          name: escheduler-master
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1
              memory: 4Gi
            requests:
              cpu: 1
              memory: 1Gi
          command:
            - /opt/entrypoint.sh
            - /opt/mntcephutils/entry/entrypoint.sh
          env:
            - name: BD_ESCHEDULER_ROLE
              value: master-server
            - name: BD_MYSQL_SERVER
              value: %MYSQL_SERVER%
            - name: BD_MYSQL_USERNAME
              value: %MYSQL_USERNAME%
            - name: BD_MYSQL_PASSWD
              value: "%MYSQL_PASSWD%"
            - name: BD_SUITE_PREFIX
              value: %PREFIX%
            - name: BD_ZOOKEEPER_SERVERS
              value: %ZK%
          volumeMounts:
            - mountPath: /opt/mntcephutils/entry
              name: utilsentry
              readOnly: true
            - mountPath: /opt/escheduler/data
              name: %PREFIX%-escheduler-backend-data
              readOnly: false
      storage:
        - name: %PREFIX%-escheduler-backend-data
      volumes:
        - configMap:
            name: %PREFIX%-easyscheduler-entry
          name: utilsentry
        - configMap:
            name: %PREFIX%-easyscheduler-sql
          name: utilssql
